import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Column from './components/container/Column.js'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [ tasks, setTasks ] = useState([]);
  const [ filteredTasks, setFilteredTasks ] = useState({});

  useEffect(() => {
    fetch(`/api/tasks`)
        .then(res => res.json())
        .then(res => {
          setTasks(state => res);
        })
        .catch(err => {
          console.log(err);
        });
  }, []);

  useEffect(() => {
    let columns = {};

    // filter all tasks into columns
    tasks.map((item) => {
      if (!columns[item.column]) {
        columns[item.column] = [];
      }
      columns[item.column].push(item);
    });

    setFilteredTasks(state => columns);
  }, [tasks]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Taskman[ager]
        </h1>

        <div className={styles.board}>
          <Column columnTasks={filteredTasks.work} setTasks={setTasks} title="Work"></Column>
          <Column columnTasks={filteredTasks.uni} setTasks={setTasks} title="Uni"></Column>
          <Column columnTasks={filteredTasks.chores} setTasks={setTasks} title="Chores"></Column>
          <Column columnTasks={filteredTasks.personal_projects} setTasks={setTasks} title="Personal projects"></Column>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>&copy; Taditech 2021</p>
      </footer>
    </div>
  )
}
